project:
    type: tufte
    resources:
    - Data/*
book:
  open-graph: true
  site-url: https://georgiadoing.github.io/Doing-Lab-Notebook/
  repo-url: https://github.com/georgiadoing/Doing-Lab-Notebook/
  repo-actions: [edit, issue]
  title: |
    Doing-Lab-Notebook
  title-short: DCBlab # title-short is used in the pdf head
  output-file: DCBlabnotes # outputs: docs/TufteStyledBook.pdf
  author: doingg@union.edu
  publisher: self
  date-format: MMMM, YYYY
  license: "CC BY"
  chapters:
    - index.qmd
    - 02-Main/schedule.qmd
    - part: Assignments
      chapters:
         - 03-Assignments/csc243_hw00.qmd
    - part: Weekly Notes
      chapters:
         - 04-Notes/week1.qmd
    - part: about.qmd
      chapters:
        - 03-Back/references.qmd
bibliography: references.bib

format:
  pdf:
    pdf-engine: xelatex
    microtype: false
    classoption: [sfsidenotes]
