---
title: HW 01
---


# CSC/BIO 243: Assignment 1

* Remember to check the schedule for readings: <https://georgiadoing.github.io/CSC243-S26/02-Main/schedule.html>
* Over the weekend
    + finish reading Bioinformatics for Dummies Ch. 1 & 2 and 
    + begin the reading  Think Python Ch. 1-3 or Molecular & Cell Biology for Dummies Ch. 1,6 and 7
    + you will want to be caught up on the reading since we will have our **first quiz next Wed of Fri**
    + I can answer any questions about materials from readings on Monday, ahead of the quiz

## Part 1

* [Intro Survey](https://forms.gle/K6unS25LTBV8GhWR8)
* Read the Therac25 case study summary and one more detailed article (linked in [week1 notes](https://georgiadoing.github.io/CSC243-S26/04-Notes/week1.html), you can choose one of the two longer articles on the notes page or find another if you prefer. Read critically and carefully and come to class **Wednesday 4/1/26** ready to discuss.

## Part 2 

* Prepare a 5 minute introduction to a topic for which you bring background knowledge to this class
    + you can use slides, write on the board and/or have me post/print out handouts
* Each topic will be presented at the beginning of the relevent class day: [Topic Sign-up and Schedule](https://docs.google.com/spreadsheets/d/1eUot5yk3xrcPYS0SuBMvblX5aYyQyh6xAZLZ4-MlWqI/edit?usp=sharing)
* Based on the results on the survey, I have done my best to match students to topics they are already familiar with, HOWEVER, you should MOVE or ADD your name so you are comfortable with your topic
* Up to 2 students can sign up for each topic
* Questions that arise as you are preparing your topic are great reasons to come to office hours, I am happy to work with you!
* **This presentation will earn you one quiz grade, "Quiz 0" (5% of your final grade)**