---
title: Resources
---

## Slides from Presentations

* check for updates often
* [Folder of slides](https://drive.google.com/drive/folders/1eRWOepFs8YGM99-1k_D8uMlPNqXi4EAF?usp=sharing) includes student presentations and lecture slides
* use student presentation slides to make up missed engagement points

## Amoeba Sisters

* videos (and more!) explaining bio topics: <https://www.amoebasisters.com/>

## Python

* Python 3.13.X: the software package needed to write and run Python programs
* <https://www.anaconda.com/download/success?reg=skipped>

## Python Documentation

* Official Documentaion: <https://docs.python.org/3/index.html>
* Can *always* be used as a reference
* Can be searched for module-specific documentation e.g. turtle

## Think Python

* online version of python texbook: <https://allendowney.github.io/ThinkPython/>
* scroll down to see the interactice google colab notebooks you can *copy to your google drive* and edit for practice

## Rosalind Problems

* for python practice: [Python Village](https://rosalind.info/problems/list-view/?location=python-village)
* for more bioinformatics problems: [Bioinformatics Stronghold](https://rosalind.info/problems/list-view/?location=python-village)
* practice using existing tools (databases, webservers, etc.): [Bioinformatics Armory](https://rosalind.info/problems/list-view/?location=bioinformatics-armory)

## Runestone (interactive python practice)

* [register](https://runestone.academy/runestone/default/user/register) for an online python practice course (free)
* enter the following as the course name: unioncollege_csc243_spring26
* check out chapters on variables, loops, functions and more python syntax
* includes small practice problems to help you become familiar with useful code
* Runestone has many other open-access online texbooks as well: <https://runestone.academy/ns/books/index>

## Gradescope: used to submit programming assignments
* <https://www.gradescope.com/courses/1287277>
* Entry Code:G6J44N


## Google Colab Pro

* Pro account sign-up: <https://colab.research.google.com/signup>
* Use your Union email
* A pro account is not needed for this course, just an option Union pays for

* Notes template: <https://colab.research.google.com/drive/15rPmKyQKCCbwsdDCpC39o8hczWZ-B5zV?usp=sharing>


## Python Style Guide 

* PEP 8
* should be used in all code cells of Colab notebooks
* Link: <https://peps.python.org/pep-0008/>


## Computer Labs

*	Olin 107 
*	PASTA Lab (ISEC 051+)
*	Computer Science Resource room (Steinmetz Hall, 209A)

## For help on your homework and projects, available to your are:

* 	CS Helpdesk (Olin 107, Sun-Thurs 7:00-9:00pm)
*	Biology Backup (ISEC 316, Tues & Thurs 5:30-7:30pm)